version: '3'
services:
  proxy:
    restart: always
    build:
      context: ./proxy
    ports:
      - ${PROXY_HTTP_EXTERNAL_PORT}:80
      - ${PROXY_HTTPS_EXTERNAL_PORT}:443
    volumes:
      - ./.logs/nginx/:/var/log/nginx/
      - ./inventory/localhost_ssl/localhost.key:/etc/nginx/ssl/rootCA.key
      - ./inventory/localhost_ssl/localhost.crt:/etc/nginx/ssl/rootCA.crt
    extra_hosts:
      - "docker_playground.dev.localhost:127.17.0.1"
    links:
      - nginx
    depends_on:
      - nginx

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - ${NGINX_HTTP_EXTERNAL_PORT}:80
    volumes:
      - ./php/app:/var/www
      - ./.logs/nginx/:/var/log/nginx/
      - ./inventory/localhost_ssl/localhost.key:/etc/nginx/ssl/rootCA.key
      - ./inventory/localhost_ssl/localhost.crt:/etc/nginx/ssl/rootCA.crt
    links:
      - php
    depends_on:
      - php

  php:
    restart: always
    build:
      context: ./php
    volumes:
      - ./php/app/:/var/www
      - ./shared_folder:/tmp/shared_folder
    links:
      - database
    depends_on:
      - database

  database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./inventory/SQL/sample.sql:/docker-entrypoint-initdb.d/sample.sql